"""Configuration variables"""

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 720
FPS = 60
BACKGROUND_COLOR = "sky blue"

PLAYER_SIZE = 120
PLAYER_SPRITE_PATH = "./images/player.jpg"
INITIAL_DASH_COOLDOWN = 1

INITIAL_SPEED_UNIT = "mm/s"
INITIAL_SPEED_COLOR = "black"