"""Configuration variables"""

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 720
FPS = 60
BACKGROUND_COLOR = "sky blue"
FONT_NAME = "Arial"
FONT_SIZE = 30

PLAYER_SIZE = 120
PLAYER_SPRITE_PATH = "./images/player-new.png"
INITIAL_DASH_COOLDOWN = 1

SPEED_METER_POSITION = (SCREEN_WIDTH / 2 - PLAYER_SIZE, 0)
SPEED_MAX_POSITION = (SCREEN_WIDTH / 2 - (PLAYER_SIZE - FONT_SIZE), FONT_SIZE + 7)
SPEED_UNITS = {"1": "mm/s", "1000": "m/s", "1000000": "km/s"}
INITIAL_SPEED_COLOR = "black"

DASH_BAR_POSITION = (10, 690)
DASH_BAR_LENGTH = 100
DASH_BAR_HEIGHT = 20
